---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
conditions <- list.files("../to_store/")

```


```{r}
lookup_table <- data.frame()
for (my_condition in conditions){
  # split the string
  my_split <- strsplit(my_condition, "_")[[1]] #|\\=
  # extract parameters
  change_what <- my_split[1]
  pos_interval <- NA
  strat_interval <- NA
  assign(paste0(change_what, "_interval"), as.numeric(my_split[2]))
  is_scaled <- my_split[3]
  init_strat <- my_split[4]
  init_pos <- my_split[5]
  male_dist <- as.numeric(my_split[6])
  num_males <- as.numeric(my_split[7])
  

  lookup_table <- rbind(lookup_table, 
                        data.frame(directory=my_condition,
                                   change_what=change_what,
                                   pos_interval=pos_interval,
                                   strat_interval=strat_interval,
                                   is_scaled=is_scaled,
                                   init_strat=init_strat,
                                   init_pos=init_pos,
                                   male_dist=male_dist,
                                   num_males=num_males))
}
```

```{r}
all_results <- tibble()
for (my_condition in conditions){
  # read and load each result
  my_dir_results <- paste0("../to_store/", my_condition, "/results/")
 my_results <- list.files(my_dir_results)
 if (length(my_results) > 0){
   # process a single file
   for (my_file in my_results) {
     my_rnd_seed <- as.numeric(strsplit(my_file, "_")[[1]][2])
     tmp <- read_csv(paste0(my_dir_results, my_file), col_types = cols()) %>% add_column(rnd_seed = my_rnd_seed, directory = my_condition, is_selection=1)

     all_results <- rbind(all_results, tmp)
   }
 }
}

for (my_condition in conditions){
  # read and load each result
  my_dir_nulls <- paste0("../to_store/", my_condition, "/nulls/")
 my_nulls <- list.files(my_dir_nulls)
 if (length(my_nulls) > 0){
   # process a single file
   for (my_file in my_nulls) {
     my_rnd_seed <- as.numeric(strsplit(my_file, "_")[[1]][2])
     tmp <- read_csv(paste0(my_dir_nulls, my_file), col_types = cols()) %>% add_column(rnd_seed = my_rnd_seed, directory = my_condition, is_selection=0)

     all_results <- rbind(all_results, tmp)
   }
 }
}

all_results <- all_results %>% inner_join(lookup_table)
```
```{r}
#ideas: var in interbower distance over time, var in matings over time

```



```{r}
mvovergen <- all_results %>% group_by(rnd_seed,gen,directory, is_selection) %>% summarise(mate_var=var(successful_mating))
```


```{r}
scaled = mvovergen %>% filter(directory=='pos_0.1_1_All.VHigh_EvenTenthClumped_900_6')
```



```{r}
pl <- ggplot(data = scaled%>% filter(gen<10)) + aes(x = gen, y = mate_var, color = as.factor(is_selection), group=interaction(rnd_seed,is_selection)) + geom_line( alpha=.2)
pl

#now the matings are a result
```

```{r}
pl <- ggplot(data = scaled%>%filter(is_selection==1)) + aes(x = gen, y = mate_var, alpha=.2) + geom_point()# , color = as.factor(is_selection), group=interaction(rnd_seed,is_selection)) + geom_line( alpha=.2)
pl

```
```{r}

dat <-scaled%>%filter(is_selection==1)
model<-lm(mate_var~gen,data = dat) #is there an error here?
summary(model)


#significantly negative slope -- mating success variance is going down with generations *slightly*

#but does this tell us anything on it's own? I think we need to know if this slope is significantly different from the slope of for the null (once we fix the mating success). In both, we expect the birds to be spreading out regardless and that could be causing it

#also, the relationship probably something more like a saturation curve. It's not going to be a line.

```
```{r}
strat_scaled = mvovergen %>% filter(directory=='strat_0.75_1_All.High_UniformJittered_900_6')
#this was a real quick example: 2 simulations, 100 gens
```

```{r}
pl <- ggplot(data = strat_scaled) + aes(x = gen, y = mate_var, color = as.factor(is_selection), group=interaction(rnd_seed,is_selection)) + geom_line( alpha=.2)
pl

#is_selection 0 and 1 potentially look the same
#but really we need more than 2 simulations
```

```{r}
stratovergen <- all_results %>% group_by(rnd_seed,gen,directory, is_selection) %>% summarise(avg_strat=mean(probability_maraud)) %>% filter(directory=='strat_0.75_1_All.High_UniformJittered_900_6')

```

```{r}
pl <- ggplot(data = stratovergen) + aes(x = gen, y = avg_strat, color = as.factor(is_selection), group=interaction(rnd_seed,is_selection)) + geom_line( alpha=.2)
pl

#same story as before

```

```{r}
library(tidyverse)
conditions <- list.files("../to_store/")[3:6]

#list.files("../to_run/incomplete_results/")
```

```{r}
lookup_table <- data.frame()
for (my_condition in conditions){
  # split the string
  my_split <- strsplit(my_condition, "_")[[1]] #|\\=
  # extract parameters
  change_what <- my_split[1]
  pos_interval <- NA
  strat_interval <- NA
  assign(paste0(change_what, "_interval"), as.numeric(my_split[2]))
  is_scaled <- my_split[3]
  init_strat <- my_split[4]
  init_pos <- my_split[5]
  male_dist <- as.numeric(my_split[6])
  num_males <- as.numeric(my_split[7])
  

  lookup_table <- rbind(lookup_table, 
                        data.frame(directory=my_condition,
                                   change_what=change_what,
                                   pos_interval=pos_interval,
                                   strat_interval=strat_interval,
                                   is_scaled=is_scaled,
                                   init_strat=init_strat,
                                   init_pos=init_pos,
                                   male_dist=male_dist,
                                   num_males=num_males))
}
```

```{r}
all_results <- tibble()
my_dir_results <- "../to_run/incomplete_results/"
my_results <- list.files("../to_run/incomplete_results/")
count=1
for (my_file in my_results) {
  my_condition <- str_remove(str_remove(str_remove(my_file, "null_.._"), "res_.._"), ".csv")
  my_rnd_seed <- as.numeric(strsplit(my_file, "_")[[1]][2])
  tmp <- read_csv(paste0(my_dir_results, my_file), col_types = cols()) %>% add_column(rnd_seed = my_rnd_seed, directory = my_condition, is_selection=(count>30))
  all_results <- rbind(all_results, tmp)
  count <-count+1
}
all_results <- all_results %>% inner_join(lookup_table) 
all_results2 <- all_results %>% filter(gen<750) #different lengths, so we're putting them all at the same length

```
```{r}
stratovergen <- all_results2 %>% group_by(rnd_seed,gen, male_dist, is_selection) %>% summarise(avg_strat=mean(probability_maraud))
```


```{r}
model1 <- glm(avg_strat ~ gen + is_selection + male_dist, # one sex as baseline, the other modifies intercept
              data = stratovergen,
              family = "binomial")
summary(model1)

```
```{r}
model2 <- glm(avg_strat ~ gen * is_selection * male_dist, 
              data = stratovergen,
              family = "binomial")
summary(model2)

```